"""new tables inscripciones and cursos and updated models with new fields

Revision ID: 253cd6b371d9
Revises: aab40a26bcf6
Create Date: 2026-03-19 08:48:52.977312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253cd6b371d9'
down_revision = 'aab40a26bcf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
